### ISSUE TITLE
Publish for JDK 8, test on JDK 11+?

### ISSUE THREAD

**Issue by armanbilge** [gemini-hlsw/clue#326]
Currently clue has a dependency on the http4s-jdk-http-client, which requires Java 11.

Now that there is a common web socket client API in https://github.com/http4s/http4s/pull/5520, it should be possible to make this library agnostic to the backend and remove the dependency on the jdk-http-client (and thus on JDK 11). This would allow you to publish for JDK 8.

Of course, testing would still require the jdk-http-client for now, so those would have to compile/run on JDK 11. Hopefully we'll get an ember-client websocket backend in the future that runs on JDK8 (and also Node.js :).

**Comment by rpiaggio** [comment]
Can we close this issue? I think it is addressed in https://github.com/gemini-hlsw/clue/pull/345 ?

**Comment by armanbilge** [comment]
It's not fully address actually (we are still publishing from JDK 11) but it is definitely possible to implement now. I can set it up.
